// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nawzmawrattfytvyrnog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hd3ptYXdyYXR0Znl0dnlybm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTIyNTYsImV4cCI6MjA2NjQyODI1Nn0.PXHOszKRkTiq01W5vp6TgqtIVvFxZkHaxcvSuSw9iX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);